/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EeAmbulanceWlList {
    }
}
declare global {
    interface HTMLEeAmbulanceWlListElement extends Components.EeAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLEeAmbulanceWlListElement: {
        prototype: HTMLEeAmbulanceWlListElement;
        new (): HTMLEeAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "ee-ambulance-wl-list": HTMLEeAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface EeAmbulanceWlList {
    }
    interface IntrinsicElements {
        "ee-ambulance-wl-list": EeAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ee-ambulance-wl-list": LocalJSX.EeAmbulanceWlList & JSXBase.HTMLAttributes<HTMLEeAmbulanceWlListElement>;
        }
    }
}
